apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
  namespace: default
spec:
  selector:
    name: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

